# Hardware-specific Constants

SERVO_INVERSE_MAX_SPEED = 0.16 / 60

SERVO_TOLERANCE = 1

SERVO_ZERO_POSITION = {2: 475 * 0.24, 3: 475 * 0.24, 4: 475 * 0.24, 5: 500 * 0.24}

HIP_SERVO_RANGE = 475 * 0.24
KNEE_SERVO_RANGE = 425 * 0.24

HIP_SERVO_MIN_POSITION = {i: SERVO_ZERO_POSITION[i] - HIP_SERVO_RANGE for i in range(2, 6)}
HIP_SERVO_MAX_POSITION = {i: SERVO_ZERO_POSITION[i] + HIP_SERVO_RANGE for i in range(2, 6)}

KNEE_SERVO_MIN_POSITION = {i: SERVO_ZERO_POSITION[i] - KNEE_SERVO_RANGE for i in range(2, 6)}
KNEE_SERVO_MAX_POSITION = {i: SERVO_ZERO_POSITION[i] + KNEE_SERVO_RANGE for i in range(2, 6)}

# Firmware-specific Constants

FL_HIP_SERVO_ID = 2
FL_KNEE_SERVO_ID = 3

FR_HIP_SERVO_ID = 4
FR_KNEE_SERVO_ID = 5