# Hardware-specific Constants

SERVO_INVERSE_MAX_SPEED = 0.16 / 60

SERVO_TOLERANCE = 1

SERVO_ZERO_POSITION = 475 * 0.24

HIP_SERVO_RANGE = 475 * 0.24
KNEE_SERVO_RANGE = 425 * 0.24

HIP_SERVO_MIN_POSITION = SERVO_ZERO_POSITION - HIP_SERVO_RANGE
HIP_SERVO_MAX_POSITION = SERVO_ZERO_POSITION + HIP_SERVO_RANGE

KNEE_SERVO_MIN_POSITION = SERVO_ZERO_POSITION - KNEE_SERVO_RANGE
KNEE_SERVO_MAX_POSITION = SERVO_ZERO_POSITION + KNEE_SERVO_RANGE

# Firmware-specific Constants

FL_HIP_SERVO_ID = 2
FL_KNEE_SERVO_ID = 3

FR_HIP_SERVO_ID = 4
FR_KNEE_SERVO_ID = 5